kind: Pod
apiVersion: v1
metadata:
  name: testpod
  annotations:
    description: our first test pod
spec: 
  containers:
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c" , "while true; do echo hello-mastan; sleep 5; done"]
