apiVersion: v1
kind: Pod
metadata:
  name: testpod4
spec:
  containers:
  - name: c05
    image: ubuntu
    command:  ["/bin/bash", "-c", "while true; do echo hello-mastan; sleep 5; done"]
    env:
    - name: MYNAME
      value: mastan
      