apiVersion: v1
kind: Pod
metadata:
  name: testpod6
  labels:
    env: dev
spec:
  containers:
  - name: c07
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo hello-mastan; sleep 5; done"]
  nodeSelector:
     hardware: t2-medium