apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
spec:
  replicas: 3
  selector:
     myname: mastan
  template:
    metadata:
      name: rcpod
      labels:
        myname: mastan
    spec:
      containers:
      - name: myrcc
        image: ubuntu    
